Fault n. 1 detected at pattern n. 8
Fault n. 2 detected at pattern n. 52
Fault n. 3 detected at pattern n. 43
Fault n. 4 detected at pattern n. 52
Fault n. 5 detected at pattern n. 111
Fault n. 6 detected at pattern n. 87
Fault n. 7 detected at pattern n. 87
Fault n. 8 detected at pattern n. 1
Fault n. 9 detected at pattern n. 2
Fault n. 10 detected at pattern n. 1
Fault n. 11 detected at pattern n. 2
Fault n. 12 detected at pattern n. 1
Fault n. 13 detected at pattern n. 87
Fault n. 14 detected at pattern n. 1
Fault n. 15 detected at pattern n. 111
Fault n. 16 detected at pattern n. 1
Fault n. 17 detected at pattern n. 52
Fault n. 18 detected at pattern n. 1
Fault n. 19 detected at pattern n. 10
Fault n. 20 detected at pattern n. 20
Fault n. 21 detected at pattern n. 10
Fault n. 22 detected at pattern n. 15
Fault n. 23 detected at pattern n. 20
Fault n. 24 detected at pattern n. 51
Fault n. 25 detected at pattern n. 10
Fault n. 26 detected at pattern n. 14
Fault n. 27 detected at pattern n. 10
Fault n. 28 detected at pattern n. 14
Fault n. 29 detected at pattern n. 136
Fault n. 30 detected at pattern n. 20
Fault n. 31 detected at pattern n. 15
Fault n. 32 detected at pattern n. 123
Fault n. 33 detected at pattern n. 42
Fault n. 34 detected at pattern n. 14
Fault n. 35 detected at pattern n. 42
Fault n. 36 detected at pattern n. 14
Fault n. 37 detected at pattern n. 111
Fault n. 38 detected at pattern n. 15
Fault n. 39 detected at pattern n. 14
Fault n. 40 detected at pattern n. 20
Fault n. 41 detected at pattern n. 86
Fault n. 42 detected at pattern n. 3
Fault n. 43 detected at pattern n. 86
Fault n. 44 detected at pattern n. 2
Fault n. 45 detected at pattern n. 3
Fault n. 46 detected at pattern n. 136
Fault n. 47 detected at pattern n. 43
Fault n. 48 detected at pattern n. 3
Fault n. 49 detected at pattern n. 43
Fault n. 50 detected at pattern n. 2
Fault n. 51 detected at pattern n. 231
Fault n. 52 detected at pattern n. 3
Fault n. 53 detected at pattern n. 29
Fault n. 54 detected at pattern n. 112
Fault n. 55 detected at pattern n. 3
Fault n. 56 detected at pattern n. 112
Fault n. 57 detected at pattern n. 2
Fault n. 58 undetected
Fault n. 59 detected at pattern n. 3
Fault n. 60 detected at pattern n. 164
Fault n. 61 detected at pattern n. 87
Fault n. 62 detected at pattern n. 2
Fault n. 63 detected at pattern n. 42
Fault n. 64 detected at pattern n. 20
Fault n. 65 detected at pattern n. 136
Fault n. 66 detected at pattern n. 111
Fault n. 67 detected at pattern n. 2
Fault n. 68 detected at pattern n. 52
Fault n. 69 detected at pattern n. 188
Fault n. 70 detected at pattern n. 87
Fault n. 71 detected at pattern n. 52
Fault n. 72 detected at pattern n. 2
Fault n. 73 detected at pattern n. 87
Fault n. 74 undetected
Fault n. 75 detected at pattern n. 87
Fault n. 76 detected at pattern n. 87
Fault n. 77 detected at pattern n. 2
Fault n. 78 detected at pattern n. 2
Fault n. 79 detected at pattern n. 86
Fault n. 80 detected at pattern n. 111
Fault n. 81 detected at pattern n. 2
Fault n. 82 detected at pattern n. 2
Fault n. 83 detected at pattern n. 112
Fault n. 84 detected at pattern n. 52
Fault n. 85 detected at pattern n. 2
Fault n. 86 detected at pattern n. 42
Fault n. 87 detected at pattern n. 2
Fault n. 88 detected at pattern n. 111
Fault n. 89 detected at pattern n. 87
Fault n. 90 detected at pattern n. 111
Fault n. 91 detected at pattern n. 87
Fault n. 92 detected at pattern n. 87
Fault n. 93 detected at pattern n. 87
Fault n. 94 detected at pattern n. 87
Fault n. 95 detected at pattern n. 43
Fault n. 96 detected at pattern n. 5
Fault n. 97 detected at pattern n. 43
Fault n. 98 detected at pattern n. 3
Fault n. 99 detected at pattern n. 63
Fault n. 100 detected at pattern n. 43
Fault n. 101 detected at pattern n. 5
Fault n. 102 detected at pattern n. 29
Fault n. 103 detected at pattern n. 43
Fault n. 104 detected at pattern n. 10
Fault n. 105 detected at pattern n. 15
Fault n. 106 detected at pattern n. 87
Fault n. 107 detected at pattern n. 3
Fault n. 108 detected at pattern n. 42
Fault n. 109 detected at pattern n. 14
Fault n. 110 detected at pattern n. 19
Fault n. 111 detected at pattern n. 15
Fault n. 112 detected at pattern n. 43
Fault n. 113 detected at pattern n. 3
Fault n. 114 undetected
Fault n. 115 detected at pattern n. 111
Fault n. 116 detected at pattern n. 111
Fault n. 117 detected at pattern n. 7
Fault n. 118 undetected
Fault n. 119 detected at pattern n. 111
Fault n. 120 undetected
Fault n. 121 undetected
Fault n. 122 detected at pattern n. 112
Fault n. 123 detected at pattern n. 111
Fault n. 124 detected at pattern n. 10
Fault n. 125 detected at pattern n. 20
Fault n. 126 detected at pattern n. 217
Fault n. 127 detected at pattern n. 42
Fault n. 128 detected at pattern n. 14
Fault n. 129 detected at pattern n. 86
Fault n. 130 detected at pattern n. 86
Fault n. 131 detected at pattern n. 2
Fault n. 132 detected at pattern n. 42
Fault n. 133 detected at pattern n. 86
Fault n. 134 detected at pattern n. 2
Fault n. 135 detected at pattern n. 111
Fault n. 136 detected at pattern n. 2
Fault n. 137 undetected
Fault n. 138 detected at pattern n. 111
Fault n. 139 detected at pattern n. 2
Fault n. 140 detected at pattern n. 110
Fault n. 141 detected at pattern n. 111
Fault n. 142 detected at pattern n. 100
Fault n. 143 detected at pattern n. 43
Fault n. 144 detected at pattern n. 43
Fault n. 145 detected at pattern n. 43
Fault n. 146 detected at pattern n. 29
Fault n. 147 detected at pattern n. 52
Fault n. 148 detected at pattern n. 43
Fault n. 149 detected at pattern n. 34
Fault n. 150 undetected
Fault n. 151 undetected
Fault n. 152 detected at pattern n. 10
Fault n. 153 detected at pattern n. 19
Fault n. 154 detected at pattern n. 10
Fault n. 155 detected at pattern n. 75
Fault n. 156 detected at pattern n. 52
Fault n. 157 detected at pattern n. 42
Fault n. 158 detected at pattern n. 42
Fault n. 159 detected at pattern n. 42
Fault n. 160 detected at pattern n. 87
Fault n. 161 detected at pattern n. 86
Fault n. 162 detected at pattern n. 20
Fault n. 163 detected at pattern n. 52
Fault n. 164 detected at pattern n. 75
Fault n. 165 undetected
Fault n. 166 undetected
Fault n. 167 detected at pattern n. 189
Fault n. 168 detected at pattern n. 52
Fault n. 169 detected at pattern n. 136
Fault n. 170 detected at pattern n. 302
Fault n. 171 detected at pattern n. 43
Fault n. 172 detected at pattern n. 43
Fault n. 173 detected at pattern n. 136
Fault n. 174 detected at pattern n. 43
Fault n. 175 undetected
Fault n. 176 undetected
Fault n. 177 detected at pattern n. 177
Fault n. 178 undetected
Fault n. 179 detected at pattern n. 203
Fault n. 180 undetected
Fault n. 181 detected at pattern n. 259
Fault n. 182 detected at pattern n. 134
Fault n. 183 detected at pattern n. 7
Fault n. 184 detected at pattern n. 203
Fault n. 185 detected at pattern n. 112
Fault n. 186 undetected
Fault n. 187 detected at pattern n. 87
Fault n. 188 detected at pattern n. 7
Fault n. 189 detected at pattern n. 2
Fault n. 190 undetected
Fault n. 191 detected at pattern n. 112
Fault n. 192 undetected
Fault n. 193 detected at pattern n. 258
Fault n. 194 detected at pattern n. 111
Fault n. 195 undetected
Fault n. 196 detected at pattern n. 298
Fault n. 197 undetected
Fault n. 198 detected at pattern n. 42
Fault n. 199 detected at pattern n. 136
Fault n. 200 detected at pattern n. 10
Fault n. 201 detected at pattern n. 42
Fault n. 202 detected at pattern n. 2
Fault n. 203 detected at pattern n. 87
Fault n. 204 detected at pattern n. 87
Fault n. 205 undetected
Fault n. 206 detected at pattern n. 87
Fault n. 207 detected at pattern n. 2
Fault n. 208 detected at pattern n. 2
Fault n. 209 undetected
Fault n. 210 detected at pattern n. 298
Fault n. 211 detected at pattern n. 87
Fault n. 212 detected at pattern n. 204
Fault n. 213 detected at pattern n. 136
Fault n. 214 detected at pattern n. 111
Fault n. 215 detected at pattern n. 136
Fault n. 216 detected at pattern n. 10
Fault n. 217 detected at pattern n. 42
Fault n. 218 detected at pattern n. 86
Fault n. 219 detected at pattern n. 2
Fault n. 220 detected at pattern n. 111
Fault n. 221 detected at pattern n. 244
Fault n. 222 detected at pattern n. 52
Fault n. 223 undetected
Fault n. 224 undetected
Fault n. 225 undetected
Fault n. 226 undetected
Fault n. 227 detected at pattern n. 87
Fault n. 228 detected at pattern n. 136
Fault n. 229 undetected
Fault n. 230 undetected
Fault n. 231 detected at pattern n. 10
Fault n. 232 detected at pattern n. 136
Fault n. 233 detected at pattern n. 42
Fault n. 234 detected at pattern n. 86
Fault n. 235 detected at pattern n. 2
Fault n. 236 detected at pattern n. 2
Fault n. 237 detected at pattern n. 217
Fault n. 238 detected at pattern n. 86
Fault n. 239 detected at pattern n. 2
Fault n. 240 detected at pattern n. 87
Fault n. 241 detected at pattern n. 136
Fault n. 242 undetected
Fault n. 243 undetected
Fault n. 244 detected at pattern n. 136
Fault n. 245 undetected
Fault n. 246 undetected
Fault n. 247 detected at pattern n. 284
Fault n. 248 detected at pattern n. 86
Fault n. 249 detected at pattern n. 244
Fault n. 250 detected at pattern n. 87
Fault n. 251 detected at pattern n. 217
Fault n. 252 detected at pattern n. 87
Fault n. 253 detected at pattern n. 52
Fault n. 254 undetected
Fault n. 255 detected at pattern n. 188
Fault n. 256 detected at pattern n. 20
Fault n. 257 detected at pattern n. 188
Fault n. 258 detected at pattern n. 52
Fault n. 259 detected at pattern n. 14
Fault n. 260 detected at pattern n. 188
Fault n. 261 detected at pattern n. 10
Fault n. 262 detected at pattern n. 136
Fault n. 263 detected at pattern n. 42
Fault n. 264 detected at pattern n. 86
Fault n. 265 detected at pattern n. 2
Fault n. 266 detected at pattern n. 20
Fault n. 267 detected at pattern n. 52
Fault n. 268 detected at pattern n. 14
Fault n. 269 detected at pattern n. 43
Fault n. 270 detected at pattern n. 298
Fault n. 271 detected at pattern n. 110
Fault n. 272 undetected
Fault n. 273 detected at pattern n. 42
Fault n. 274 detected at pattern n. 150
Fault n. 275 detected at pattern n. 203
Fault n. 276 detected at pattern n. 203
Fault n. 277 detected at pattern n. 262
